### ISSUE TITLE
Reloading only displays 1 side of 14-segment display

### ISSUE THREAD

**Issue by Tyler-R** [SFU-Embedded-Cosplay/Halo-Gun#2]
When the Gun reaches 0 ammo and reloads only 1 side of the 14 segment display will light up.  It would be nice if both digits lit up when reloading.  The fix is likely in this section of code, but we should ensure that both digits light up when reloading from a Bluetooth command as well.

``` C
if (amountOfAmmo == 0) {
    delay(1000);
    reload();
}
```

**Comment by landalex** [comment]
I believe this is a regression, I never noticed this problem in the past. 

I don't believe that delay affects the display at all. The main loop will alternate between turning the left and right sides off independently of everything else (reloading, sending/receiving Bluetooth), specifically in this piece of code:

``` C
  if (showLeftNumber) {
    digitalWrite(LEFT_NUMBER_DISPLAY, HIGH);
    digitalWrite(RIGHT_NUMBER_DISPLAY, LOW);
    showLeftNumber = false;
  } else {
    digitalWrite(LEFT_NUMBER_DISPLAY, LOW);
    digitalWrite(RIGHT_NUMBER_DISPLAY, HIGH);
    showLeftNumber = true;
  }
```

**Comment by Tyler-R** [comment]
It looks like the both the reloading and switching between sides of the display are done on the same thread in the main loop meaning that when `delay(1000)` is called the main thread will sleep for 1 second and not change the display between the left and right side.  I don't think there is an issue when the gun is reloaded over Bluetooth, but I have not tested it.  

Assuming my assumption is correct, my recommendation would be to replace the `delay(1000)` call with a method that would alternate between the left and right side of the display for 1000ms, to simulate a 1 second pause after running out of ammo while still maintaining the image on the display. We could also use this time to play audio for a reload sound if necessary.
